### ISSUE TITLE
Unused variable: dest

### ISSUE THREAD

**Issue by Poikilos** [bobjacobsen/PythonOlcbNode#2]
```diff
-                if destt == None:
-                    dest = NodeID(0)
+                if destt is not None:
+                    dest = NodeID(0)
```

~~I'm not 100% sure I know the right thing to do here to fix the area of code, so maybe let's come back to this after the next PR.~~ Ok, I accidentally reversed the logic. Now it makes sense. PR will include correct change:
```diff
-                if destt == None:
-                    dest = NodeID(0)
+                if destt is None:
+                    destt = NodeID(0)
```

**Comment by bobjacobsen** [comment]
Thanks.  Your commit comment mentions "static analysis".  Is there some tool that you recommend for checking Python like this?

**Comment by Poikilos** [comment]
- pycodestyle checks PEP8 comprehensively including very surface-level stuff--This is what could be most properly called a "linter" since it mostly covers code formatting and style, but can also turn up mistakes caused by unusual use of variables or uninitialized variables etc.
- PyLance does deeper analysis. 
- Flake8 is a combination of both of the above, more or less, and has many extensions available for code practices that could cause potential issues. If you were to use only one, I'd recommend this with the extensions added as well.
- The ruff extension for VSCode (or fully open-source VSCodium) checks for various issues including one or more of the above automatically. I'm not sure if it automatically uses all of them but I also usually install the Flake8 and Pylance extensions too. The main purpose of ruff is to install one extension to do all types of static analysis using Rustlang for speed.

All of the above can also be used on the command line and most IDEs can be configured to have real-time checking or you can add it to a button in Geany for example (click-to-navigate to errors is possible if using a linter command argument setting it to an output style recognizable to Geany, if you place it in Geany's first two command slots in Build, Set Build Commands while having a py file open already which triggers the Python settings there). I recommend ruff since it tries to combine functionality of all of the others and is fast, but Flake8 is very good if various Flake8 extensions are installed.
