### ISSUE TITLE
example_node_implementation has a hard-coded localNodeID

### ISSUE THREAD

**Issue by Poikilos** [bobjacobsen/PythonOlcbNode#28]
Should the node ID be determined by the network somehow in a real situation? If possible please update example or explain. I will read the LCC Standard again but have trouble connecting it to practicals.

**Comment by bobjacobsen** [comment]
Each node has to have a unique  node ID assigned when it is constructed.

For example, a hardware node will have its unique node ID programmed into it as part of assembling the node.  The ID is usually written on the board somewhere so it can be found for configuration after installing it on the layout.

For these examples, that's called `localNodeID`.  I gave it a value from the range that's assigned to me (see http://registry.openlcb.org/uniqueidranges). If a real node was made from these examples, other unique value(s) should be assigned.

Some of these examples reach out and touch another node, e.g. to send it a datagram.  A node ID is also needed for that (though see some of the tests in OlcbChecker for an example of "find a node, any node"), so I entered a value as `farNodeID`.  The value I gave it was the CS-105 that I have on my desk.  Your value for that would vary.

When creating a node like a RR-Cirkits node board, you don't really have to worry about the far node.  The only time such a board needs to specifically address another node is when that other node has issued a request to it.  I.e. You'll get the node ID from the other node dynamically as it requests you to talk to it, and you can just reply using that info.

Node like JMRI or a firmware downloader are query the network to find all the node ID that are out there, then e.g. ask the user to select one.
