### ISSUE TITLE
Possible attempt to cast using non-Pythonic code

### ISSUE THREAD

**Issue by Poikilos** [bobjacobsen/PythonOlcbNode#3]
After PR, we should figure out what this is trying to do and correct it:
- [ ] in test_localnodeprocessor.py:
```Python
self.processor : Processor = LocalNodeProcessor(LinkMockLayer(NodeID(100)))
```
  - (seems incorrect unless call returns a type(?))

- [ ] in test_datagramservice.py:
```Python
sentMessages : [Message] = []
```
(may be type hinting, unsure)

**Comment by bobjacobsen** [comment]
I think this line
```
self.processor : Processor = LocalNodeProcessor(LinkMockLayer(NodeID(100)))
```
is meant to create a `LocoNodeProcessor` that's using a mock version (supplied locally) of a `LinkLayer` that in turn is using a `NodeID` to identify the local node.  The ID of that NodeID is arbitrary, any non-zero positive number would work, so I put in 100. 

This code probably needs a few more comments....

**Comment by bobjacobsen** [comment]
Thanks for reading so carefully!

This line
```
sentMessages : [Message] = []
```
is stil in Swift syntax, and wasn't properly converted to Python.  It should be just
```
sentMessages  = []
```
without the Swift type information.

**Comment by bobjacobsen** [comment]
Oops.  I missed the type information in that 1st comment, and was replying to the wrong thing.  My apologies.

Yes, the `: Processor` part is a left-over Swift-ism that shouldn't be there.
