### ISSUE TITLE
Question about OpenLcb Configuration Nodes Tool

### ISSUE THREAD

**Issue by jeff-tcs** [bobjacobsen/PythonOlcbNode#31]
Hi Bob,
I am Jeff Snyder. I work at TCS with Jake. Thanks you for refering me too the example code for OpenLCB, in particular the code that should us how to Verify Node IDS in the LCC Network. I am in the process of writing code for TCS that will allow us to update the memory configuration on LCC network nodes to include the command station, booster and other nodes. I would like to review how the OpenLCB configuration tool code does that. Could you tell me where in github I could look at the source code?
Thanks in advance.
Jeff

**Comment by bobjacobsen** [comment]
Nice to hear from you!

I haven't written any Python code that specifically does updates, but I'd be happy to create an example.

Or are you looking for how JMRI does it?

**Comment by Poikilos** [comment]
Hello, I'm still working with @jeff-tcs still and we have been studying the Standards along with Technical Notes but have not yet connected some of the dots. The strict scope of how standards are written seems to place some information in a vacuum. For example, the CDI Standard says "This Standard does not address how the CDI is stored, retrieved, or used". @bakerstu suggested reading the Technical Note alongside the standard, but that connecting of dots excluded by the quote I mentioned also seems to be excluded from the Technical Note. This is an example of information that could be in documentation that bridges the standard with practicals, which I've started to write here: <https://docs.google.com/document/d/1MfDHIobOjfX7_h8aMQDcDFbMRpvGSv-M00S-yZF6eiI/edit?usp=sharing>. As long as we can get CDI from the device, we can go from there. An example in Python would be helpful. If you create that, I'd be glad to contribute a corresponding tkinter GUI for such an example. Then we (and people creating other projects) could code a similar one our program using a different GUI framework. At some point after that, writing a value back to the device is our current goal.

**Comment by bobjacobsen** [comment]
@Poikilos I'm working on an example that will read the CDI from a node and invoke callbacks from parsing that CDI.  I think that will get you started.  It might take a few days to get it done.

**Comment by jeff-tcs** [comment]
> Nice to hear from you!
> 
> I haven't written any Python code that specifically does updates, but I'd be happy to create an example.
> 
> Or are you looking for how JMRI does it?

No just in python...since I looked at your code for CDI config tool I know how to create the code I need...thanks. Jeff

**Comment by jeff-tcs** [comment]
ok look forward to seeing the example. Jeff

**Comment by bobjacobsen** [comment]
There's now an example in this repository named `example_cdi_access.py`.  I

 - It starts up and connects to the Node ID that's inside the example
 - It then starts a read cycle that runs until the entire CDI has been read
 - It then hands the CDI to the XML parser
 - This version just prints the elements and contents that the parse encounters

To create a GUI from this, you'd change the `startElement` and `endeElement` methods to look at the element type and contents to make the desired GUI elements.

**Comment by jeff-tcs** [comment]
Bob I downloaded the code...thank you I will be checking it out. Jeff

**Comment by bobjacobsen** [comment]
@jeff-tcs Did you get what you needed from this?

**Comment by jeff-tcs** [comment]
Ok I figured it out thanks for reaching out.
